apiVersion: apps/v1
kind: Deployment
metadata:
  name: api--order-deployment
  namespace: shoes-eks
spec:
  selector:
    matchLabels:
      app: api--order
  template: 
    metadata:
        name: api--order
        labels:
          app: api--order
    spec:
        containers:
          - name: api--order-container
            image: $dck-accountid/$dck-repository:api--order-$githash
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "dev,jsonlog"
            ports:
              - containerPort: 5000
              - containerPort: 9190
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 9190
              initialDelaySeconds: 120
              periodSeconds: 60
              timeoutSeconds: 10
              successThreshold: 1
              failureThreshold: 2
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 9190
              initialDelaySeconds: 120
              periodSeconds: 10
              timeoutSeconds: 10